# app/config/security.yml

security:
    providers:
        main:
            entity: { class: WCS\FlyaroundBundle\Entity\User, property: username }

    firewalls:
        secured_area:
           pattern:    ^/
           anonymous: ~
           form_login:
               login_path:  /login
               check_path:  /login_check
           logout:
               path:   /logout
               target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    encoders:
        WCS\FlyaroundBundle\Entity\User: sha512
