services:
#    wcs_flyaround.example:
#        class: WCS\FlyaroundBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


    wcs.flyaround.admin.fly:
        class: WCS\FlyaroundBundle\Admin\FlyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: fly, label: Flies }
        arguments: [null, WCS\FlyaroundBundle\Entity\Fly, WCSFlyaroundBundle:FlyAdmin]

    wcs.flyaround.admin.terrain:
        class: WCS\FlyaroundBundle\Admin\TerrainAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: fly, label: Terrains }
        arguments: [null, WCS\FlyaroundBundle\Entity\Terrain, WCSFlyaroundBundle:TerrainAdmin]

    wcs.flyaround.admin.user:
        class: WCS\FlyaroundBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Administration, label: User }
        arguments: [null, WCS\FlyaroundBundle\Entity\User, WCSFlyaroundBundle:UserAdmin]
